### PR TITLE
Fix kal-select

### LINKED ISSUE #67: Cannot disable kal-select
You can't disable the kal-select with a reactive form.

`this.control.disable()` doesn't work.

### PR DESCRIPTION
**Pull request by Bellico**

### CODE REVIEW

File: projects/kalidea/kaligraphi/src/lib/molecules/kal-select/kal-select.component.ts [hunk 1]
```diff
@@ -318,7 +327,7 @@ export class KalSelectComponent
   /**
    * Event emitted when several options are selected
    * Set the option as active
-   * @param option KalOptionComponent
+   * @param options KalOptionComponent
```
Comment (ydomenjoud) [inline projects/kalidea/kaligraphi/src/lib/molecules/kal-select/kal-select.component.ts:330]: if you provide js doc for function args, you should explain their purpose and not type ( which are already set by Typescript )

**Review by ydomenjoud — APPROVED** [review]
